### ISSUE TITLE
Code Missing

### ISSUE THREAD

**Issue by hendrycks** [automl/nes#1]
This is an important paper. Any word on when its code will be released?

**Comment by arberzela** [comment]
Hi Dan,

Thanks a lot for reading our paper and your assessment! We are doing some final refactoring and testing and we hope to open-source the codebase withing a week or so.

Cheers,
Arber

**Comment by hendrycks** [comment]
Great!

**Comment by arberzela** [comment]
Apologies for the one week extra delay from what we promised! Now the code is uploaded. Please let us know if you encounter any issues or if you have any questions.

Cheers,
Arber and Sheh
