### ISSUE TITLE
Plans to release searched architectures?

### ISSUE THREAD

**Issue by nutellamok** [automl/nes#2]
Dear authors, 

I find this a truly impactful and interesting paper and am currently trying to utilize NES for one of my projects.
However, with my computing budget, training all baselearners individually and evaluating them to construct NES will take up a tremendous amount of time and resources.

Thus, I was wondering if you had plans to release searched architectures for the sake of quick deployment. 

Thank you!

**Comment by arberzela** [comment]
Hi,

Thank you very much for your interest in our work! Do you maybe have any particular dataset & search space that you would like to get the searched architectures? It would be easier for us due to the large amount of experiments in the paper.

Best,
Arber
